### ISSUE TITLE
Xyce contains conflicts with mpich

### ISSUE THREAD

**Issue by yurivict** [Xyce/Xyce#85]
These errors came up when MPI was enabled in Trilinos:
```
../../src/ParallelDistPKG/N_PDS_Serial.h:62:18: error: redefinition of 'MPI_Op'
static const int MPI_BAND = 0;
                 ^
/usr/local/include/mpi.h:306:22: note: expanded from macro 'MPI_BAND'
#define MPI_BAND    (MPI_Op)(0x58000006)
                     ^
../../src/ParallelDistPKG/N_PDS_Serial.h:57:18: note: previous definition is here
static const int MPI_MAX = 0;
                 ^
/usr/local/include/mpi.h:301:22: note: expanded from macro 'MPI_MAX'
#define MPI_MAX     (MPI_Op)(0x58000001)
                     ^
In file included from N_ANP_MOR.C:73:
../../src/ParallelDistPKG/N_PDS_Serial.h:62:26: error: expected ';' after top level declarator
static const int MPI_BAND = 0;
                         ^
                         ;
../../src/ParallelDistPKG/N_PDS_Serial.h:63:18: error: redefinition of 'MPI_Op'
static const int MPI_LOR = 0;
                 ^
/usr/local/include/mpi.h:307:22: note: expanded from macro 'MPI_LOR'
#define MPI_LOR     (MPI_Op)(0x58000007)
                     ^
../../src/ParallelDistPKG/N_PDS_Serial.h:57:18: note: previous definition is here
static const int MPI_MAX = 0;
                 ^
/usr/local/include/mpi.h:301:22: note: expanded from macro 'MPI_MAX'
#define MPI_MAX     (MPI_Op)(0x58000001)
                     ^
In file included from N_ANP_MOR.C:73:
../../src/ParallelDistPKG/N_PDS_Serial.h:63:25: error: expected ';' after top level declarator
static const int MPI_LOR = 0;
                        ^
                        ;
../../src/ParallelDistPKG/N_PDS_Serial.h:64:18: error: redefinition of 'MPI_Op'
static const int MPI_BOR = 0;
                 ^
/usr/local/include/mpi.h:308:22: note: expanded from macro 'MPI_BOR'
#define MPI_BOR     (MPI_Op)(0x58000008)
                     ^
../../src/ParallelDistPKG/N_PDS_Serial.h:57:18: note: previous definition is here
static const int MPI_MAX = 0;
                 ^
/usr/local/include/mpi.h:301:22: note: expanded from macro 'MPI_MAX'
#define MPI_MAX     (MPI_Op)(0x58000001)
                     ^
In file included from N_ANP_MOR.C:73:
../../src/ParallelDistPKG/N_PDS_Serial.h:64:25: error: expected ';' after top level declarator
static const int MPI_BOR = 0;
                        ^
                        ;
```

Xyce-7.6.0
clang-14
FreeBSD 13.1

**Comment by tvrusso** [comment]
This is a sign that you have incorrectly configured trilinos for a parallel build.  When you follow our directions for building both Trilinos and Xyce for parallel, this will not happen.

How have you configured trilinos?

And since your build is referencing /usr/local/mpi.h, this is a sign that you are building Xyce against MPICH, which is very much not recommended.  Xyce's performance with MPICH on FreeBSD is abyssmal.  You should be using OpenMPI.

Note that because MPICH installs to /usr/local and OpenMPI installs to /usr/local/mpi/openmpi, the mere presence of MPICH is a problem for Xyce when built against OpenMPI.

All of this is warned about in our building guide.

If you are not following the building guide's recommendations, you're on your own.

**Comment by tvrusso** [comment]
Also, please note that the Xyce team does not formally support FreeBSD, even though I have been building Xyce on FreeBSD for over 20 years.   I am retiring shortly, and the team's willingness to support FreeBSD will basically retire with me.  Nobody on the team will be able to address quirks of the FreeBSD ports system.  The Xyce team does not have the resources to support FreeBSD's port system, especially when not abiding by our build recommendations.

The problem here lies with the ports system and the choices that have been made in the MPICH port, which gleefully dumps its headers and libraries right in /usr/local/include and /usr/local/lib, making them conflict at link time with OpenMPI.

**Comment by yurivict** [comment]
> And again, if you choose to ignore our guidance and do something else that we specifically recommend you not do, you're gonna have a bad day.

I don't choose this. How do you imagine Trilinos can be built specifically for Xyce w/in the ports system? There has to be one Trilinos build for all users. Trilinos is now at version 13.4.1, and your instructions recommend to use 12.12.1.

**Comment by yurivict** [comment]
> Trying to do a one-size-fits-all Trilinos build and dumping directly into /usr/local/lib and /usr/local/include is a mistake.

Xyce actually builds fine with the latest Trilinos, it only needs ```-DXyce_PARALLEL_MPI``` that configure fails to set.
I think that this is a bug in Xyce.

**Comment by tvrusso** [comment]
This is not a bug in Xyce.  Xyce_PARALLEL_MPI is set when you add the "--enable-mpi" option to configure.
